# Generated by Django 4.1.3 on 2022-12-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='classes.grade', verbose_name='Класс ученика'),
        ),
    ]
