# Generated by Django 4.1.3 on 2022-12-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0002_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher', verbose_name='Идентификатор учителя'),
        ),
    ]
