# Generated by Django 4.1.3 on 2022-12-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0005_alter_student_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher', verbose_name='Идентификатор учителя'),
        ),
    ]
