# Generated by Django 4.1.3 on 2022-12-22 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0006_alter_student_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mark_attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classes.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher')),
            ],
        ),
    ]
