# Generated by Django 4.1.3 on 2022-12-22 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0007_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(null=True, verbose_name='Причина отсутствия'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mark_attendance',
            field=models.CharField(choices=[(1, 'Присутствовал'), (2, 'Отсутсвовал'), (3, 'Отсутсвовал по уважительной причине')], max_length=50, verbose_name='Отметка посещаемости'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='classes.student', verbose_name='Идентификатор ученика'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher', verbose_name='Идентификатор учителя'),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
    ]
