# Generated by Django 4.1.3 on 2022-12-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_canteenemployee'),
        ('classes', '0008_alter_attendance_options_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher'),
        ),
    ]
