# Generated by Django 4.1.3 on 2022-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_grade_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark_attendance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Присутствовал'), (2, 'Отсутсвовал'), (3, 'Отсутсвовал по уважительной причине')], default=1, verbose_name='Отметка посещаемости'),
        ),
    ]
