# Generated by Django 4.1.3 on 2022-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_remove_grade_meal_time_grade_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtime',
            name='meal_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Полдник')], default=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='meal_time',
            field=models.ManyToManyField(default=1, to='classes.mealtime', verbose_name='Время приёма пищи'),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='meal_end',
            field=models.TimeField(verbose_name='Окончание приёма пищи'),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='meal_start',
            field=models.TimeField(verbose_name='Начало приёма пищи'),
        ),
    ]
