# Generated by Django 4.1.3 on 2022-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_mealtime_meal_category_alter_grade_meal_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='meal_time',
            field=models.ManyToManyField(to='classes.mealtime', verbose_name='Время приёма пищи'),
        ),
    ]
