# Generated by Django 4.1.3 on 2022-12-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_attendance_grade_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.grade', verbose_name='Иденитификатор класса'),
        ),
    ]
