# Generated by Django 4.1.3 on 2022-12-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_alter_attendance_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
    ]
