# Generated by Django 4.1.3 on 2022-12-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_remove_student_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtime',
            name='meal_category',
        ),
    ]
