# Generated by Django 4.1.3 on 2022-12-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_mealcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealCategory',
        ),
    ]
