# Generated by Django 4.1.3 on 2022-12-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_mealcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtime',
            name='meal_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.mealcategory'),
        ),
    ]
