# Generated by Django 4.1.3 on 2022-12-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_mealtime_meal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
