# Generated by Django 4.1.3 on 2022-12-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_attendance_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='meal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.mealcategory', verbose_name='Приём пищи'),
        ),
    ]
