# Generated by Django 4.1.3 on 2023-01-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0028_alter_attendance_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='mark_attendance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Присутствовал'), (2, 'Отсутствовал'), (3, 'Отсутствовал по уважительной причине')], default=1, verbose_name='Отметка посещаемости'),
        ),
    ]
