# Generated by Django 4.1.3 on 2023-02-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_alter_attendance_mark_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='name',
        ),
    ]
