# Generated by Django 4.1.3 on 2023-02-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_administration_administrator'),
        ('classes', '0030_rename_grade_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher', verbose_name='Учитель класса'),
        ),
    ]
