# Generated by Django 4.2 on 2023-05-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_alter_grade_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='mark_attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_attendance', models.PositiveSmallIntegerField(choices=[(1, 'Присутствовал'), (2, 'Отсутствовал'), (3, 'Отсутствовал по уважительной причине')], default=1, verbose_name='Отметка посещаемости')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отсутствия')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='classes.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student', verbose_name='Идентификатор ученика')),
            ],
            options={
                'verbose_name': 'Посещаемость студента',
                'verbose_name_plural': 'Посещаемость студента',
                'db_table': 'student_attendance',
            },
        ),
    ]
