# Generated by Django 4.2 on 2023-05-14 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0033_rename_reason_studentattendance_absent_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='meal_category',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_grade', to='classes.grade', verbose_name='Иденитификатор класса'),
        ),
        migrations.CreateModel(
            name='GradeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата посещения')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_attendances', to='classes.attendance')),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.mealcategory', verbose_name='Приём пищи')),
            ],
            options={
                'verbose_name': 'Посещаемость класса',
                'verbose_name_plural': 'Посещаемость класса',
                'db_table': 'grade_attendance',
            },
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='grade_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='classes.gradeattendance'),
        ),
    ]
