# Generated by Django 4.1.3 on 2022-12-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_canteenemployee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='canteenemployee',
            table='canteen_empl',
        ),
    ]
