# Generated by Django 4.1.3 on 2022-12-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_canteenemployee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.AddField(
            model_name='parent',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
