# Generated by Django 4.1.3 on 2023-01-26 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_administration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administration',
            new_name='Administrator',
        ),
    ]
