# Generated by Django 4.1.3 on 2022-12-20 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='meal_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед')], default=1),
        ),
    ]
