# Generated by Django 4.1.3 on 2022-12-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Полдник')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='meal_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завтрак'), (2, 'Обед'), (3, 'Полдник')], default=1),
        ),
    ]
