# Generated by Django 4.1.3 on 2022-12-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_meal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meal_category',
        ),
    ]
