# Generated by Django 4.1.3 on 2022-12-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_mealcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealCategory',
        ),
    ]
