# Generated by Django 4.1.3 on 2022-12-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_mealtime_meal_category'),
        ('orders', '0009_delete_mealcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meal_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classes.mealcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='meal_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classes.mealcategory'),
        ),
    ]
