# Generated by Django 4.1.3 on 2023-02-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_meal_category_product_meal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
