# Generated by Django 4.1.3 on 2023-03-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_menuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.menu'),
        ),
    ]
