# Generated by Django 4.1.3 on 2023-03-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_menu_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem'),
        ),
    ]
