# Generated by Django 4.1.3 on 2023-03-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_menu_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='orders.menu'),
            preserve_default=False,
        ),
    ]
