# Generated by Django 4.1.3 on 2023-03-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_alter_grade_teacher'),
        ('orders', '0025_menu_active_menu_date_implementation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal_category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classes.mealcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Выбрать текущим меню на сегодня'),
        ),
    ]
