# Generated by Django 4.1.3 on 2023-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_cart_product_created_product_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
