# Generated by Django 4.1.3 on 2023-04-10 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_name_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=256, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
