# Generated by Django 4.1.3 on 2023-04-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_rename_menu_id_menuitem_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInCart',
            new_name='CartItem',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
