# Generated by Django 4.1.3 on 2023-04-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_rename_productincart_cartitem_alter_cartitem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prod_count',
            new_name='quantity',
        ),
    ]
