# Generated by Django 4.1.3 on 2023-04-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_rename_prod_count_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины покупателей'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
