# Generated by Django 4.1.3 on 2023-04-19 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_alter_grade_teacher'),
        ('orders', '0035_alter_cart_options_rename_title_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_student', to='classes.student', verbose_name='Ученик'),
        ),
    ]
