# Generated by Django 4.1.3 on 2023-04-23 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_administration_administrator'),
        ('orders', '0037_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer', to='accounts.parent', verbose_name='Покупатель'),
        ),
    ]
