# Generated by Django 4.1.3 on 2023-04-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_cartitem_product_remove_order_meal_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_menu',
            new_name='product',
        ),
    ]
