# Generated by Django 4.1.3 on 2023-04-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_rename_product_menu_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_menu', to='orders.menu', verbose_name='Меню корзины'),
        ),
    ]
