# Generated by Django 4.1.3 on 2023-04-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_cart_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
