# Generated by Django 4.1.3 on 2023-04-25 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_remove_cart_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_added',
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=False, help_text='Нужно ли активировать данное меню?', verbose_name='Выбрать текущим меню на выбранную дату'),
        ),
    ]
